routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/icon', function () {
    return view('icon');
});

//web profile

Route::get('/webProfile','WebProfileController@getHome')->name('webProfile');
Route::get('/webProfileTentang','WebProfileController@getProfile')->name('tentang');
Route::get('/webProfileLaptop','WebProfileController@getLaptop')->name('laptop');
Route::get('/webProfileGaming','WebProfileController@getGaming')->name('gaming');
Route::get('/webProfileNotebook','WebProfileController@getNotebook')->name('notebook');
Route::get('/webProfileNetbook','WebProfileController@getNetbook')->name('netbook');
Route::get('/webProfileMacbook','WebProfileController@getMacbook')->name('macbook');


//dynamic
//Route::get('/webProfile/{category}','webProfileController@category');


//redirect back
// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');

//fix with true false auth
Route::get('login','authController@getLogin')->name('login');
Route::post('login','authController@postLogin')->name('login');


//redirect in /home
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

//register/create user
Route::get('register','authController@getRegister')->name('register');
Route::post('register','authController@postRegister');


	Route::group(['prefix' => '/dashboard', 'as' => 'dashboard.'], function () {
		Route::get('/data', 'dashboardController@index')->name('dashboard');
		Route::get('/chart', 'chartController@index')->name('chartbar');
	});

	//BARANG
	Route::group(['prefix' => '/barang', 'as' => 'barang.'], function () {
		Route::get('/data','barangController@index')->name('index');
		Route::get('/create','barangController@create')->name('create');
		Route::post('/store','barangController@store')->name('store');
		Route::get('/{id}/edit','barangController@edit')->name('edit');
		Route::get('/{id}/show','barangController@show')->name('show');
		Route::put('/{id}/update','barangController@update')->name('update');
		Route::delete('/{id}/destroy','barangController@destroy')->name('destroy');
	});

	//KATEGORI
	Route::group(['prefix' => '/kategori', 'as' => 'kategori.'], function () {
		Route::get('/data','kategoriController@index')->name('index');
		Route::get('/create','kategoriController@create')->name('create');
		Route::post('/store','kategoriController@store')->name('store');
		Route::get('/{id}/edit','kategoriController@edit')->name('edit');
		Route::get('/{id}/show','kategoriController@show')->name('show');
		Route::put('/{id}/update','kategoriController@update')->name('update');
		Route::delete('/{id}/destroy','kategoriController@destroy')->name('destroy');
	});

	//SUPPLIER
	Route::group(['prefix' => '/supplier', 'as' => 'supplier.'], function () {
		Route::get('/data','supplierController@index')->name('index');
		Route::get('/create','supplierController@create')->name('create');
		Route::post('/store','supplierController@store')->name('store');
		Route::get('/{id}/edit','supplierController@edit')->name('edit');
		Route::get('/{id}/show','supplierController@show')->name('show');
		Route::put('/{id}/update','supplierController@update')->name('update');
		Route::delete('/{id}/destroy','supplierController@destroy')->name('destroy');
	});

	//CUSTOMER
	Route::group(['prefix' => '/customer', 'as' => 'customer.'], function () {
		Route::get('/data','customerController@index')->name('index');
		Route::get('/create','customerController@create')->name('create');
		Route::post('/store','customerController@store')->name('store');
		Route::get('/{id}/edit','customerController@edit')->name('edit');
		Route::get('/{id}/show','customerController@show')->name('show');
		Route::put('/{id}/update','customerController@update')->name('update');
		Route::delete('/{id}/destroy','customerController@destroy')->name('destroy');
	});

	//USER
	Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
		Route::get('/data','userController@index')->name('index');
		Route::get('/create','userController@create')->name('create');
		Route::post('/store','userController@store')->name('store');
		Route::get('/{id}/edit','userController@edit')->name('edit');
		Route::get('/{id}/show','userController@show')->name('show');
		Route::put('/{id}/update','userController@update')->name('update');
		Route::delete('/{id}/destroy','userController@destroy')->name('destroy');
	});

	//TRANSAKSI-MASUK
	Route::group(['prefix' => '/transaksi-masuk', 'as' => 'transaksi-masuk.'], function () {
		Route::get('/data','transaksiController@index')->name('index');
		Route::get('/create','transaksiController@create')->name('create');
		Route::post('/store','transaksiController@store')->name('store');
		Route::get('/{id}/show','transaksiController@show')->name('show');
	});

	Route::get('/CariHarga','transaksiController@CariHarga');
	Route::get('/CariJumlah','transaksiController@CariJumlah');

	//TRANSAKSI-KELUAR
	Route::group(['prefix' => '/transaksi-keluar', 'as' => 'transaksi-keluar.'], function () {
		Route::get('/data','transaksikeluarController@index')->name('index');
		Route::get('/create','transaksikeluarController@create')->name('create');
		Route::post('/store','transaksikeluarController@store')->name('store');
		Route::get('/{id}/show','transaksikeluarController@show')->name('show');
	});

	Route::get('/CariHargaK','transaksikeluarController@CariHargaK');
	Route::get('/CariJumlahK','transaksikeluarController@CariJumlahK');


	//RETUR-NEW
	//RETUR-KELUAR
	Route::group(['prefix' => '/retur-keluar', 'as' => 'retur-keluar.'], function () {
		Route::get('/data','returController@index')->name('index');
		Route::get('/create','returController@create')->name('create');
		Route::post('/store','returController@store')->name('store');
		Route::get('/{id}/show','returController@show')->name('show');
	});

	Route::get('/CariBarang','returController@CariBarang');
	Route::get('/CariJumlahRetur','returController@CariJumlahRetur');
	Route::get('/CariCustRetur','returController@CariCustRetur');


	//TRANSAKSI-MASUK
	Route::group(['prefix' => '/retur-masuk', 'as' => 'retur-masuk.'], function () {
		Route::get('/data','returMasukController@index')->name('index');
		Route::get('/create','returMasukController@create')->name('create');
		Route::post('/store','returMasukController@store')->name('store');
		Route::get('/{id}/show','returMasukController@show')->name('show');
	});

	Route::get('/CariBarang','returMasukController@CariBarang');
	Route::get('/CariJumlahRetur','returMasukController@CariJumlahRetur');
	Route::get('/CariSupRetur','returMasukController@CariSupRetur');

	//LAPORAN
	Route::get('/laporan-membership','dashboardController@getLaporanMember');
	Route::post('/getDataMember','dashboardController@getDataMember')->name('getDataMember');

	Route::get('/laporan-barang','dashboardController@getLaporanBarang');
	Route::post('/getDataBarang','dashboardController@getDataBarang')->name('getDataBarang');
	
	Route::get('/laporan-transaksi','dashboardController@getLaporanTrans');
	Route::post('/getDataTrans','dashboardController@getDataTrans')->name('getDataTrans');

	Route::get('/laporan-retur','dashboardController@getLaporanRetur');
	Route::post('/getDataRetur','dashboardController@getDataRetur')->name('getDataRetur');
	
	//LOGS
	Route::get('/logs-masuk','LogsController@getLapMasuk');
	Route::post('/getDataLapKeluar','LogsController@getDataLapKeluar')->name('getDataLapKeluar');

	Route::get('/logs-keluar','LogsController@getLapKeluar');
	Route::post('/getDataLapMasuk','LogsController@getDataLapMasuk')->name('getDataLapMasuk');

	Route::get('/logs-retur-masuk','LogsController@getLapRMasuk');
	Route::post('/getDataLapRMasuk','LogsController@getDataLapRMasuk')->name('getDataLapRMasuk');

	Route::get('/logs-retur-keluar','LogsController@getLapRKeluar');
	Route::post('/getDataLapRKeluar','LogsController@getDataLapRKeluar')->name('getDataLapRKeluar');

	Route::get('logout', 'Auth\LoginController@logout');

	Route::get('/datatransaksi','transaksiKeluarController@JenisBarang');
	Route::get('/datauang','transaksiKeluarController@uang');


//dashboard
// Route::get('dashboard', 'dashboardController@index')->name('dashboard');


//route resource for crud action
// Route::resource('user','userController')->middleware('auth');
// Route::resource('customer','customerController')->middleware('auth');
// Route::resource('supplier','supplierController')->middleware('auth');
// Route::resource('kategori','kategoriController')->middleware('auth');
// Route::resource('barang','barangController')->middleware('auth');
// Route::resource('transaksi','transaksiController')->middleware('auth');
// Route::get('dashboard', 'dashboardController@index')->middleware('auth')->name('dashboard');
// Route::resource('retur','returController')->middleware('auth');

// Route::get('logout', 'Auth\LoginController@logout')->name('logout');


//grouping middleware
// Route::group(['middleware' => 'auth'],function(){
	// Route::get('dashboard', 'dashboardController@index')->name('dashboard');

	// Route::get('dashboard/chart', 'chartController@index')->name('chartbar');
	
	// Route::resource('user','userController');
	
	// Route::resource('customer','customerController');


app/barang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class barang extends Model
{
    protected $fillable = [
        'nama_barang', 'kode_barang', 'id_kategori', 'jumlah', 'harga', 'foto_barang','deskripsi',
    ]; 
  
    public function kategori()
    {
        return $this->belongsTo(kategori::class);   
    }

     public function logs()
    {
        return $this->hasMany(logs::class);
    }


    use SoftDeletes;
    protected $dates =['deleted_at'];
}

app/Http/Controllers/barangController.php
<?php

namespace App\Http\Controllers;

use App\barang;
use App\User;
use App\kategori;
use App\suplier;
use App\Http\Controllers\DB;
use App\Http\Controllers\View;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\userController;
use App\Http\Controllers\kategoriController;
use App\Http\Controllers\supplierController;
use Illuminate\Database\Query\Builder;

class barangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //table name
         $barangs = \DB::table('barangs')          
        -> join('kategoris', 'barangs.id_kategori', '=', 'kategoris.id')
       // -> join('users', 'barangs.id_user', '=', 'users.id')
        //-> join('supliers', 'barangs.id_suplier', '=', 'supliers.id')
        -> select('barangs.id','barangs.nama_barang', 'barangs.kode_barang','kategoris.nama_kategori','barangs.jumlah','barangs.harga','barangs.foto_barang','barangs.deskripsi','barangs.created_at','barangs.updated_at')            
        ->where('barangs.deleted_at', null) 
        ->get();
        return view ('barang.masterbarang',compact('barangs')); 
        
        // dd($barangs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $maxId = \DB::table('barangs')->max('id');
        $maxId= $maxId + 1;

        $users = User::all();
        $kategoris = kategori::all();
        $suppliers = suplier::all();

        return view ('barang.createbarang')
        ->with(compact('users'))
        ->with(compact('kategoris'))
        ->with(compact('suppliers'))
        ->with(compact('maxId'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $success = 'failed';

        $barang = barang::create([
            'nama_barang'=> $request->nama_barang,
            'kode_barang'=> $request->kode_barang,
            'id_kategori'=> $request->id_kategori,
            'jumlah'=>$request->jumlah,
            'harga'=>$request->harga,
            'foto_barang'=> $request->file('foto_barang')->store('foto_barang'),
            'deskripsi'=>$request->deskripsi
        ]); 

        // $this->validate($request,[
        //     'kode_barang'=>'required|unique:barangs'
        // ]);

        $this->validate($request,[
            'foto_barang'=>'required|mimes:jpeg,jpg,png'
        ]);

        {
           $success = 'success'; 
        }
        //route('barang.index')
        return redirect()->back()->with('alert', $success);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kategoris = kategori::all();
        $suppliers = suplier::all();
        $users = user::all();
        $barangs = barang::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategoris = kategori::all();
        $suppliers = suplier::all();
        $users = user::all();
        $barangs = barang::find($id);
        
        return view('barang.editbarang',compact('kategoris', 'suppliers','users','barangs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        barang::where('id', $id)->update([
            'nama_barang' => request('nama_barang'),
            'kode_barang' => request('kode_barang'),
            'id_kategori' => request('id_kategori'),
            // 'id_suplier' => request('id_suplier'),
            // 'id_user' => request('id_user'),
            // 'jumlah' => (request('jumlah') + request('jml')),
            'jumlah' => request('jumlah'),
            'harga' => request('harga'),
            // 'foto_barang'=> $request->file('foto_barang')->store('foto_barang'),
            'deskripsi' => request('deskripsi')
        ]);

        return redirect()->route('barang.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $barangs = barang::findOrFail($id);
        $barangs->delete();

        //Session::flash('flash_message', 'Customer successfully deleted!');

        return redirect()->route('barang.index')
        ->with('delete','Anda telah berhasil menghapus produk');
        //return redirect()->route('/barang');
    }

}

resources/views/barang/masterbarang.blade.php
@extends('layout.default')

@section('title')
    Master Barang
@endsection

@section('content')
    <div class="title_right">
        <h3><a href="{{route('barang.create')}}" class="btn-index btn btn-primary pull-right col-sm-2 col-sm-10" title="Add"><i class="glyphicon glyphicon-plus"></i></a></h3>
    </div>
    <div class="title_left">
        <h3>Master Barang</h3>
    </div>

    <div class="x_panel">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Master Data</a></li>
            <li class="breadcrumb-item active"><a href="#">Barang</a></li>
        </ol>
        <div class="con">
            <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline collapsed" role="grid" aria-describedby="datatable-buttons_info" style="width: 1031px;">
                <thead>
                <tr>
                    <th scope="col">Nama Barang</th>
                    <th scope="col">Kode Barang</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Jumlah</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Gambar</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($barangs as $barang)
                <tr>
                    <td>{{ $barang->nama_barang }}</td>       
                    <td>{{ $barang->kode_barang }}</td>
                    <td>{{ $barang->nama_kategori }}</td>
                    <td>{{ $barang->jumlah }}</td>
                    <td>{{ $barang->harga }}</td>
                    <td>
                        <img src="{{ asset('storage/'.$barang->foto_barang) }}" alt="image" height="75">
                    </td>
                    <td>{{ $barang->deskripsi }}</td>
                    <td>
                        <div id="lihat-modal-{{ $barang->id}}" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">
                                            <span id="modal-title">View Master Barang</span>
                                        </h4>
                                    </div>
                                   <form action="{{ route ('barang.show', $barang->id )}}" method="GET">
                                        <div class="modal-body" value="{{ $barang->id }}">
                                        @method('GET')
                                        @csrf
                                            <div class="form-group">
                                                <label>Nama Barang </label>
                                                <div>
                                                    <input type="text" class="form-control" id="nama_barang" name="nama_barang" value="{{ $barang->nama_barang }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Kode Barang </label>
                                                <div>
                                                    <input type="text" class="form-control" id="kode_barang" name="kode_barang" value="{{ $barang->kode_barang }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Kategori</label>
                                                <div>
                                                    <input type="text" class="form-control" id="nama_kategori" name="id_kategori" value="{{ $barang->nama_kategori }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Jumlah</label>
                                                <div>
                                                    <input type="text" class="form-control" id="jumlah" name="jumlah" value="{{ $barang->jumlah }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Harga</label>
                                                <div>
                                                    <input type="text" class="form-control" id="harga" name="harga" value="{{ $barang->harga }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Deskripsi</label>
                                                <div>
                                                    <input type="text" class="form-control" id="deskripsi" name="deskripsi" value="{{ $barang->deskripsi }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Date Created</label>
                                                <div>
                                                    <input type="text" class="form-control" id="created_at" name="created_at" value="{{ $barang->created_at }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Last Modifield</label>
                                                <div>
                                                    <input type="text" class="form-control" id="updated_at" name="updated_at" value="{{ $barang->updated_at }}" disabled="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Foto Barang</label><br>
                                                <div>
                                                    <img src="{{ asset('storage/'.$barang->foto_barang) }}" alt="image" height="128">
                                                </div>
                                            </div>

                                        </div> 
                                    </form>
                                    
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="hapus-modal-{{ $barang->id  }}" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">
                                            <!-- Beri id "modal-title" untuk tag span pada judul modal -->
                                            <span id="modal-title">Apakah anda ingin menghapus <strong>{{ $barang->nama_barang }}</strong>?</span>
                                        </h4>
                                    </div>
                                    <div class="modal-footer">
                                        <form action="{{ route ('barang.destroy', $barang->id )}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                           <!-- <input type="submit" class="btn btn-default">Ya-->
                                            <button type="submit" class="btn btn-default" >Ya</button>
                                        </form>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <a href="#"  data-toggle="modal" data-target="#lihat-modal-{{ $barang->id  }}" class="btn btn-primary glyphicon glyphicon-eye-open" title="View"></a>
                        <a href="{{route('barang.edit',$barang->id)}}" class="btn btn-info glyphicon glyphicon-edit" title="Edit"></a>
                        <button data-toggle="modal" data-target="#hapus-modal-{{ $barang->id  }}" class="btn btn-danger glyphicon glyphicon-trash" ></button>

                    </td>
                </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection