routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/icon', function () {
    return view('icon');
});

//web profile

Route::get('/webProfile','WebProfileController@getHome')->name('webProfile');
Route::get('/webProfileTentang','WebProfileController@getProfile')->name('tentang');
Route::get('/webProfileLaptop','WebProfileController@getLaptop')->name('laptop');
Route::get('/webProfileGaming','WebProfileController@getGaming')->name('gaming');
Route::get('/webProfileNotebook','WebProfileController@getNotebook')->name('notebook');
Route::get('/webProfileNetbook','WebProfileController@getNetbook')->name('netbook');
Route::get('/webProfileMacbook','WebProfileController@getMacbook')->name('macbook');


//dynamic
//Route::get('/webProfile/{category}','webProfileController@category');


//redirect back
// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');

//fix with true false auth
Route::get('login','authController@getLogin')->name('login');
Route::post('login','authController@postLogin')->name('login');


//redirect in /home
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

//register/create user
Route::get('register','authController@getRegister')->name('register');
Route::post('register','authController@postRegister');


	Route::group(['prefix' => '/dashboard', 'as' => 'dashboard.'], function () {
		Route::get('/data', 'dashboardController@index')->name('dashboard');
		Route::get('/chart', 'chartController@index')->name('chartbar');
	});

	//BARANG
	Route::group(['prefix' => '/barang', 'as' => 'barang.'], function () {
		Route::get('/data','barangController@index')->name('index');
		Route::get('/create','barangController@create')->name('create');
		Route::post('/store','barangController@store')->name('store');
		Route::get('/{id}/edit','barangController@edit')->name('edit');
		Route::get('/{id}/show','barangController@show')->name('show');
		Route::put('/{id}/update','barangController@update')->name('update');
		Route::delete('/{id}/destroy','barangController@destroy')->name('destroy');
	});

	//KATEGORI
	Route::group(['prefix' => '/kategori', 'as' => 'kategori.'], function () {
		Route::get('/data','kategoriController@index')->name('index');
		Route::get('/create','kategoriController@create')->name('create');
		Route::post('/store','kategoriController@store')->name('store');
		Route::get('/{id}/edit','kategoriController@edit')->name('edit');
		Route::get('/{id}/show','kategoriController@show')->name('show');
		Route::put('/{id}/update','kategoriController@update')->name('update');
		Route::delete('/{id}/destroy','kategoriController@destroy')->name('destroy');
	});

	//SUPPLIER
	Route::group(['prefix' => '/supplier', 'as' => 'supplier.'], function () {
		Route::get('/data','supplierController@index')->name('index');
		Route::get('/create','supplierController@create')->name('create');
		Route::post('/store','supplierController@store')->name('store');
		Route::get('/{id}/edit','supplierController@edit')->name('edit');
		Route::get('/{id}/show','supplierController@show')->name('show');
		Route::put('/{id}/update','supplierController@update')->name('update');
		Route::delete('/{id}/destroy','supplierController@destroy')->name('destroy');
	});

	//CUSTOMER
	Route::group(['prefix' => '/customer', 'as' => 'customer.'], function () {
		Route::get('/data','customerController@index')->name('index');
		Route::get('/create','customerController@create')->name('create');
		Route::post('/store','customerController@store')->name('store');
		Route::get('/{id}/edit','customerController@edit')->name('edit');
		Route::get('/{id}/show','customerController@show')->name('show');
		Route::put('/{id}/update','customerController@update')->name('update');
		Route::delete('/{id}/destroy','customerController@destroy')->name('destroy');
	});

	//USER
	Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
		Route::get('/data','userController@index')->name('index');
		Route::get('/create','userController@create')->name('create');
		Route::post('/store','userController@store')->name('store');
		Route::get('/{id}/edit','userController@edit')->name('edit');
		Route::get('/{id}/show','userController@show')->name('show');
		Route::put('/{id}/update','userController@update')->name('update');
		Route::delete('/{id}/destroy','userController@destroy')->name('destroy');
	});

	//TRANSAKSI-MASUK
	Route::group(['prefix' => '/transaksi-masuk', 'as' => 'transaksi-masuk.'], function () {
		Route::get('/data','transaksiController@index')->name('index');
		Route::get('/create','transaksiController@create')->name('create');
		Route::post('/store','transaksiController@store')->name('store');
		Route::get('/{id}/show','transaksiController@show')->name('show');
	});

	Route::get('/CariHarga','transaksiController@CariHarga');
	Route::get('/CariJumlah','transaksiController@CariJumlah');

	//TRANSAKSI-KELUAR
	Route::group(['prefix' => '/transaksi-keluar', 'as' => 'transaksi-keluar.'], function () {
		Route::get('/data','transaksikeluarController@index')->name('index');
		Route::get('/create','transaksikeluarController@create')->name('create');
		Route::post('/store','transaksikeluarController@store')->name('store');
		Route::get('/{id}/show','transaksikeluarController@show')->name('show');
	});

	Route::get('/CariHargaK','transaksikeluarController@CariHargaK');
	Route::get('/CariJumlahK','transaksikeluarController@CariJumlahK');


	//RETUR-NEW
	//RETUR-KELUAR
	Route::group(['prefix' => '/retur-keluar', 'as' => 'retur-keluar.'], function () {
		Route::get('/data','returController@index')->name('index');
		Route::get('/create','returController@create')->name('create');
		Route::post('/store','returController@store')->name('store');
		Route::get('/{id}/show','returController@show')->name('show');
	});

	Route::get('/CariBarang','returController@CariBarang');
	Route::get('/CariJumlahRetur','returController@CariJumlahRetur');
	Route::get('/CariCustRetur','returController@CariCustRetur');


	//TRANSAKSI-MASUK
	Route::group(['prefix' => '/retur-masuk', 'as' => 'retur-masuk.'], function () {
		Route::get('/data','returMasukController@index')->name('index');
		Route::get('/create','returMasukController@create')->name('create');
		Route::post('/store','returMasukController@store')->name('store');
		Route::get('/{id}/show','returMasukController@show')->name('show');
	});

	Route::get('/CariBarang','returMasukController@CariBarang');
	Route::get('/CariJumlahRetur','returMasukController@CariJumlahRetur');
	Route::get('/CariSupRetur','returMasukController@CariSupRetur');

	//LAPORAN
	Route::get('/laporan-membership','dashboardController@getLaporanMember');
	Route::post('/getDataMember','dashboardController@getDataMember')->name('getDataMember');

	Route::get('/laporan-barang','dashboardController@getLaporanBarang');
	Route::post('/getDataBarang','dashboardController@getDataBarang')->name('getDataBarang');
	
	Route::get('/laporan-transaksi','dashboardController@getLaporanTrans');
	Route::post('/getDataTrans','dashboardController@getDataTrans')->name('getDataTrans');

	Route::get('/laporan-retur','dashboardController@getLaporanRetur');
	Route::post('/getDataRetur','dashboardController@getDataRetur')->name('getDataRetur');
	
	//LOGS
	Route::get('/logs-masuk','LogsController@getLapMasuk');
	Route::post('/getDataLapKeluar','LogsController@getDataLapKeluar')->name('getDataLapKeluar');

	Route::get('/logs-keluar','LogsController@getLapKeluar');
	Route::post('/getDataLapMasuk','LogsController@getDataLapMasuk')->name('getDataLapMasuk');

	Route::get('/logs-retur-masuk','LogsController@getLapRMasuk');
	Route::post('/getDataLapRMasuk','LogsController@getDataLapRMasuk')->name('getDataLapRMasuk');

	Route::get('/logs-retur-keluar','LogsController@getLapRKeluar');
	Route::post('/getDataLapRKeluar','LogsController@getDataLapRKeluar')->name('getDataLapRKeluar');

	Route::get('logout', 'Auth\LoginController@logout');

	Route::get('/datatransaksi','transaksiKeluarController@JenisBarang');
	Route::get('/datauang','transaksiKeluarController@uang');


//dashboard
// Route::get('dashboard', 'dashboardController@index')->name('dashboard');


//route resource for crud action
// Route::resource('user','userController')->middleware('auth');
// Route::resource('customer','customerController')->middleware('auth');
// Route::resource('supplier','supplierController')->middleware('auth');
// Route::resource('kategori','kategoriController')->middleware('auth');
// Route::resource('barang','barangController')->middleware('auth');
// Route::resource('transaksi','transaksiController')->middleware('auth');
// Route::get('dashboard', 'dashboardController@index')->middleware('auth')->name('dashboard');
// Route::resource('retur','returController')->middleware('auth');

// Route::get('logout', 'Auth\LoginController@logout')->name('logout');


//grouping middleware
// Route::group(['middleware' => 'auth'],function(){
	// Route::get('dashboard', 'dashboardController@index')->name('dashboard');

	// Route::get('dashboard/chart', 'chartController@index')->name('chartbar');
	
	// Route::resource('user','userController');
	
	// Route::resource('customer','customerController');


app/User.php
<?php

namespace App;


use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Notifications\DatabaseNotificationCollection;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * App\User
 *
 * @property-read DatabaseNotificationCollection|DatabaseNotification[] $notifications
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama','alamat','email','password','telp','foto_profil','jabatan',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function barang()
    {
        return $this->hasMany(barang::class);
    }

    public function transaksi()
    {
        return $this->hasMany(transaksi::class);
    }   

    public function hasRole($role)
    {
        return $this->role == $role;
    } 

    public function hasId($id)
    {
        return $this->id == $id;
    }
   
}
    

app/Http/Controllers/userController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests;
use Illuminate\Http\Request;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view ('user.masteruser',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('user.createuser');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fileName = time() . '.png';
        $user = User::create([
            'nama'=> $request->nama,
            'alamat'=> $request->alamat,
            'email'=>$request->email,
            'password'=>bcrypt($request->password),
            'telp'=> $request->telp,
            'foto_profil'=> $request->file('foto_profil')->storeAs('foto_profil',$fileName),
            'jabatan'=> $request->jabatan
        ]);

        $this->validate($request,[
            // 'email'=>'required|email|unique:users',
            'password'=>'required|min:6|confirmed',
            'foto_profil'=>'required|mimes:jpeg,jpg,png'
        ]);
        
        // auth()->loginUsingId($user->nama);
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $users = User::all();
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::find($id);
        $user = $users;
        return view('user.edituser',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $foto = User::where('id',$id)->pluck('foto_profil');
        // dd($foto);
        User::where('id', $id)->update([
            'nama'=> $request->nama,
            'alamat'=> $request->alamat,
            'email'=>$request->email,
            'password'=>bcrypt($request->password),
            'telp'=> $request->telp,
            // 'foto_profil'=> $request->file('foto_profil')!=null? $request->file('foto_profil')->store('photos'):$foto,
            'jabatan'=> $request->jabatan
        ]);
        //User::find($id)->update($request->all());
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/createuser.blade.php
@extends('layout.default')

@section('title')
  Master User - Add
@endsection

@section('content')
  <div class="title_right">
    <h3><a href="{{route('user.index')}}" class="btn-index btn btn-primary pull-right col-sm-2 col-sm-10" title="Back"><i class="fa fa-arrow-left"></i></a></h3>
  </div>
  <div class="title_left">
    <h3>Master User - Add</h3>
  </div>
  <div class="x_panel">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Membership</a></li>
      <li class="breadcrumb-item"><a href="#">User</a></li>
      <li class="breadcrumb-item active"><a href="">Add</a></li>
    </ol>
    <div class="x_content">
      @if(session('alert'))
        <div class="alert {{ session('alert') == 'success' ? 'alert-success' : 'alert-danger' }}">
            <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span>@if(session('alert') == 'success') User Berhasil Ditambahkan. @else User Gagal Ditambahkan. @endif</span>
        </div>
        @endif
        <form method="post" action="{{route ('user.store')}}" class="form-horizontal form-label-left" role="form" name="_token" enctype="multipart/form-data">
          @if($errors->isNotEmpty())
                    <div class="alert alert-warning" role="alert">
                        @foreach($errors->all() as $error)
                            <span>{{ $error }}</span>
                            <br>
                        @endforeach
                    </div>
                @endif
        {{csrf_field()}}

        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12">Nama</label>
            <div class="col-sm-5 col-xs-12">
                <input type="text" id="nama" name="nama" value="{{old('nama')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
                @if ($errors->has('nama'))
                    <span class="help-block">
                        <strong>{{ $errors->first('nama') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12">Alamat</label>
            <div class="col-sm-5 col-xs-12">
                <textarea id="alamat" name="alamat" class="form-control col-md-7 col-xs-12" rows="5"></textarea>
                @if ($errors->has('alamat'))
                  <span class="help-block">
                      <strong>{{ $errors->first('alamat') }}</strong>
                  </span>
              @endif
            </div>
        </div>

        <div class="form-group">
          <label class="control-label col-sm-3 col-xs-12">Email</label>
          <div class="col-sm-5 col-xs-12">
              <input type="email" id="email" name="email" value="{{old('email')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
              @if ($errors->has('email'))
                  <span class="help-block">
                      <strong>{{ $errors->first('email') }}</strong>
                  </span>
              @endif
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-sm-3 col-xs-12">Password</label>
          <div class="col-sm-5 col-xs-12">
              <input type="password" id="password" name="password" value="{{old('password')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
              @if ($errors->has('password'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password') }}</strong>
                  </span>
              @endif
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-sm-3 col-xs-12">Password Konfirmasi</label>
          <div class="col-sm-5 col-xs-12">
              <input type="password" id="password_confirmation" name="password_confirmation" value="{{old('password_confirmation')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
              @if ($errors->has('password_confirmation'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password_confirmation') }}</strong>
                  </span>
              @endif
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-sm-3 col-xs-12">Telp</label>
          <div class="col-sm-5 col-xs-12">
              <input type="text" class="form-control" data-inputmask="'mask' : '(999) 999-999-999'" id="telp" name="telp" value="{{old('telp')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
              @if ($errors->has('telp'))
                  <span class="help-block">
                      <strong>{{ $errors->first('telp') }}</strong>
                  </span>
              @endif
              <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
          </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3 col-xs-12">Foto Profil</label>
            <div class="col-sm-5 col-xs-7">
                <input id="foto_profil" type="file" class="form-control" onchange="validate(this.value)" name="foto_profil"">
                @if ($errors->has('foto_profil'))
                    <span class="help-block">
                        <strong>{{ $errors->first('foto_profil') }}</strong>
                    </span>
                @endif
            </div>
        </div>

        <div class="form-group">
          <label class="control-label col-sm-3 col-xs-12">Jabatan</label>
          <div class="col-sm-3 col-sm-9">
            <select class="form-control" name="jabatan" id="jabatan">
              <option value="">-</option>
              <option value="superadmin">Super Admin</option>
              <option value="admin">Admin</option>
              <option value="owner">Owner</option>
            </select>
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Add</button>
      </form>
    </div>
  </div>
@endsection
@section('script')
  <script type="text/javascript">
    function validate(file){
      var ext = file.substr(file.lastIndexOf('.')+1);
      var allow=["jpg","jpeg",'png','bmp'];
      if(allow.lastIndexOf(ext)==-1){
        $(".err").html('ERROR! The File Must Be Image!');
      }
    }
  </script>
@endsection

resources/views/user/masteruser.blade.php
@extends('layout.default')

@section('title')
    Master User
@endsection

@section('content')
    <div class="title_right">
        <h3><a href="{{route('user.create')}}" class="btn-index btn btn-primary pull-right col-sm-2 col-sm-10" title="Add"><i class="glyphicon glyphicon-plus"></i></a></h3>
    </div>
    <div class="title_left">
        <h3>Master User</h3>
    </div>

    <div class="x_panel">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Membership</a></li>
            <li class="breadcrumb-item active"><a href="">User</a></li>
        </ol>
        <div class="con">
            <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline collapsed" role="grid" aria-describedby="datatable-buttons_info" style="width: 1031px;">
                <thead>
                <tr>
                    <th scope="col">Nama</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telp</th>
                    <th scope="col">Foto</th>
                    <th scope="col">Jabatan</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                <tr>
                    <td>{{ $user->nama }}</td>       
                    <td>{{ $user->alamat }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->telp }}</td>
                    <td>
                        <img src="{{ asset('storage/'.$user->foto_profil) }}" alt="image" height="75">
                    </td>
                    <td>{{ $user->jabatan }}</td>
                    <td>
                        <div id="lihat-modal-{{ $user->id}}" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">
                                            <!-- Beri id "modal-title" untuk tag span pada judul modal -->
                                            <span id="modal-title">View Master User</span>
                                        </h4>
                                    </div>
                                    <form action="{{ route ('user.show', $user->id )}}" method="GET">
                                        <div class="modal-body" value="">
                                        

                                        <div class="form-group">
                                            <label>ID</label>
                                            <div class="">
                                                <input type="text" class="form-control" id="id" name="id" value="{{ $user->id }}" disabled="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Nama</label>
                                            <div>
                                               <input type="text" class="form-control" id="nama" name="nama" value="{{ $user->nama }}" disabled=""> 
                                            </div>                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Alamat</label>
                                            <div>
                                              <input type="text" class="form-control" id="alamat" name="alamat" value="{{ $user->alamat }}" disabled="">  
                                            </div>                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <div>
                                               <input type="text" class="form-control" id="email" name="email" value="{{ $user->email }}"disabled="" > 
                                            </div>                                         
                                        </div>
                                        <div class="form-group">
                                            <label>Telp</label>
                                            <div>
                                                <input type="text" class="form-control" id="telp" name="telp" value="{{ $user->email }}"disabled="" >
                                            </div>                                        
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>Jabatan</label>
                                            <div>
                                              <input type="text" class="form-control" id="jabatan" name="jabatan" value="{{ $user->jabatan }}" disabled="">  
                                            </div>              
                                        </div>
                                        <div class="form-group">
                                            <label>Date Created</label>
                                            <div>
                                              <input type="text" class="form-control" id="created_at" name="created_at" value="{{ $user->created_at }}" disabled="">  
                                            </div>                      
                                        </div>
                                        <div class="form-group">
                                            <label>Last Modifield</label>
                                            <div>
                                               <input type="text" class="form-control" id="updated_at" name="updated_at" value="{{ $user->updated_at }}" disabled=""> 
                                            </div>
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Foto</label><br>
                                            <div>
                                               <img src="{{ asset('storage/'.$user->foto_profil) }}" alt="image" height="128"> 
                                            </div>
                                        </div>

                                    </div>
                                </form>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <a href="#"  data-toggle="modal" data-target="#lihat-modal-{{ $user->id  }}" class="btn btn-primary glyphicon glyphicon-eye-open" title="View"></a>
                        <a href="{{route('user.edit',$user->id)}}" class="btn btn-info glyphicon glyphicon-edit" title="Edit"></a>
                    </td>
                </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection