routes/web.php
Route::get('/webProfile','WebProfileController@getHome')->name('webProfile');
Route::get('/webProfileTentang','WebProfileController@getProfile')->name('tentang');
Route::get('/webProfileLaptop','WebProfileController@getLaptop')->name('laptop');
Route::get('/webProfileGaming','WebProfileController@getGaming')->name('gaming');
Route::get('/webProfileNotebook','WebProfileController@getNotebook')->name('notebook');
Route::get('/webProfileNetbook','WebProfileController@getNetbook')->name('netbook');
Route::get('/webProfileMacbook','WebProfileController@getMacbook')->name('macbook');


//dynamic
//Route::get('/webProfile/{category}','webProfileController@category');


//redirect back
// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');

//fix with true false auth
Route::get('login','authController@getLogin')->name('login');
Route::post('login','authController@postLogin')->name('login');


//redirect in /home
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

//register/create user
Route::get('register','authController@getRegister')->name('register');
Route::post('register','authController@postRegister');


	Route::group(['prefix' => '/dashboard', 'as' => 'dashboard.'], function () {
		Route::get('/data', 'dashboardController@index')->name('dashboard');
		Route::get('/chart', 'chartController@index')->name('chartbar');
	});

	//BARANG
	Route::group(['prefix' => '/barang', 'as' => 'barang.'], function () {
		Route::get('/data','barangController@index')->name('index');
		Route::get('/create','barangController@create')->name('create');
		Route::post('/store','barangController@store')->name('store');
		Route::get('/{id}/edit','barangController@edit')->name('edit');
		Route::get('/{id}/show','barangController@show')->name('show');
		Route::put('/{id}/update','barangController@update')->name('update');
		Route::delete('/{id}/destroy','barangController@destroy')->name('destroy');
	});

	//KATEGORI
	Route::group(['prefix' => '/kategori', 'as' => 'kategori.'], function () {
		Route::get('/data','kategoriController@index')->name('index');
		Route::get('/create','kategoriController@create')->name('create');
		Route::post('/store','kategoriController@store')->name('store');
		Route::get('/{id}/edit','kategoriController@edit')->name('edit');
		Route::get('/{id}/show','kategoriController@show')->name('show');
		Route::put('/{id}/update','kategoriController@update')->name('update');
		Route::delete('/{id}/destroy','kategoriController@destroy')->name('destroy');
	});

	//SUPPLIER
	Route::group(['prefix' => '/supplier', 'as' => 'supplier.'], function () {
		Route::get('/data','supplierController@index')->name('index');
		Route::get('/create','supplierController@create')->name('create');
		Route::post('/store','supplierController@store')->name('store');
		Route::get('/{id}/edit','supplierController@edit')->name('edit');
		Route::get('/{id}/show','supplierController@show')->name('show');
		Route::put('/{id}/update','supplierController@update')->name('update');
		Route::delete('/{id}/destroy','supplierController@destroy')->name('destroy');
	});

	//CUSTOMER
	Route::group(['prefix' => '/customer', 'as' => 'customer.'], function () {
		Route::get('/data','customerController@index')->name('index');
		Route::get('/create','customerController@create')->name('create');
		Route::post('/store','customerController@store')->name('store');
		Route::get('/{id}/edit','customerController@edit')->name('edit');
		Route::get('/{id}/show','customerController@show')->name('show');
		Route::put('/{id}/update','customerController@update')->name('update');
		Route::delete('/{id}/destroy','customerController@destroy')->name('destroy');
	});

	//USER
	Route::group(['prefix' => '/user', 'as' => 'user.'], function () {
		Route::get('/data','userController@index')->name('index');
		Route::get('/create','userController@create')->name('create');
		Route::post('/store','userController@store')->name('store');
		Route::get('/{id}/edit','userController@edit')->name('edit');
		Route::get('/{id}/show','userController@show')->name('show');
		Route::put('/{id}/update','userController@update')->name('update');
		Route::delete('/{id}/destroy','userController@destroy')->name('destroy');
	});

	//TRANSAKSI-MASUK
	Route::group(['prefix' => '/transaksi-masuk', 'as' => 'transaksi-masuk.'], function () {
		Route::get('/data','transaksiController@index')->name('index');
		Route::get('/create','transaksiController@create')->name('create');
		Route::post('/store','transaksiController@store')->name('store');
		Route::get('/{id}/show','transaksiController@show')->name('show');
	});

	Route::get('/CariHarga','transaksiController@CariHarga');
	Route::get('/CariJumlah','transaksiController@CariJumlah');

	//TRANSAKSI-KELUAR
	Route::group(['prefix' => '/transaksi-keluar', 'as' => 'transaksi-keluar.'], function () {
		Route::get('/data','transaksikeluarController@index')->name('index');
		Route::get('/create','transaksikeluarController@create')->name('create');
		Route::post('/store','transaksikeluarController@store')->name('store');
		Route::get('/{id}/show','transaksikeluarController@show')->name('show');
	});

	Route::get('/CariHargaK','transaksikeluarController@CariHargaK');
	Route::get('/CariJumlahK','transaksikeluarController@CariJumlahK');


	//RETUR-NEW
	//RETUR-KELUAR
	Route::group(['prefix' => '/retur-keluar', 'as' => 'retur-keluar.'], function () {
		Route::get('/data','returController@index')->name('index');
		Route::get('/create','returController@create')->name('create');
		Route::post('/store','returController@store')->name('store');
		Route::get('/{id}/show','returController@show')->name('show');
	});

	Route::get('/CariBarang','returController@CariBarang');
	Route::get('/CariJumlahRetur','returController@CariJumlahRetur');
	Route::get('/CariCustRetur','returController@CariCustRetur');


	//TRANSAKSI-MASUK
	Route::group(['prefix' => '/retur-masuk', 'as' => 'retur-masuk.'], function () {
		Route::get('/data','returMasukController@index')->name('index');
		Route::get('/create','returMasukController@create')->name('create');
		Route::post('/store','returMasukController@store')->name('store');
		Route::get('/{id}/show','returMasukController@show')->name('show');
	});

	Route::get('/CariBarang','returMasukController@CariBarang');
	Route::get('/CariJumlahRetur','returMasukController@CariJumlahRetur');
	Route::get('/CariSupRetur','returMasukController@CariSupRetur');

	//LAPORAN
	Route::get('/laporan-membership','dashboardController@getLaporanMember');
	Route::post('/getDataMember','dashboardController@getDataMember')->name('getDataMember');

	Route::get('/laporan-barang','dashboardController@getLaporanBarang');
	Route::post('/getDataBarang','dashboardController@getDataBarang')->name('getDataBarang');
	
	Route::get('/laporan-transaksi','dashboardController@getLaporanTrans');
	Route::post('/getDataTrans','dashboardController@getDataTrans')->name('getDataTrans');

	Route::get('/laporan-retur','dashboardController@getLaporanRetur');
	Route::post('/getDataRetur','dashboardController@getDataRetur')->name('getDataRetur');
	
	//LOGS
	Route::get('/logs-masuk','LogsController@getLapMasuk');
	Route::post('/getDataLapKeluar','LogsController@getDataLapKeluar')->name('getDataLapKeluar');

	Route::get('/logs-keluar','LogsController@getLapKeluar');
	Route::post('/getDataLapMasuk','LogsController@getDataLapMasuk')->name('getDataLapMasuk');

	Route::get('/logs-retur-masuk','LogsController@getLapRMasuk');
	Route::post('/getDataLapRMasuk','LogsController@getDataLapRMasuk')->name('getDataLapRMasuk');

	Route::get('/logs-retur-keluar','LogsController@getLapRKeluar');
	Route::post('/getDataLapRKeluar','LogsController@getDataLapRKeluar')->name('getDataLapRKeluar');

	Route::get('logout', 'Auth\LoginController@logout');

	Route::get('/datatransaksi','transaksiKeluarController@JenisBarang');
	Route::get('/datauang','transaksiKeluarController@uang');


//dashboard
// Route::get('dashboard', 'dashboardController@index')->name('dashboard');


//route resource for crud action
// Route::resource('user','userController')->middleware('auth');
// Route::resource('customer','customerController')->middleware('auth');
// Route::resource('supplier','supplierController')->middleware('auth');
// Route::resource('kategori','kategoriController')->middleware('auth');
// Route::resource('barang','barangController')->middleware('auth');
// Route::resource('transaksi','transaksiController')->middleware('auth');
// Route::get('dashboard', 'dashboardController@index')->middleware('auth')->name('dashboard');
// Route::resource('retur','returController')->middleware('auth');

// Route::get('logout', 'Auth\LoginController@logout')->name('logout');


//grouping middleware
// Route::group(['middleware' => 'auth'],function(){
	// Route::get('dashboard', 'dashboardController@index')->name('dashboard');

	// Route::get('dashboard/chart', 'chartController@index')->name('chartbar');
	
	// Route::resource('user','userController');
	
	// Route::resource('customer','customerController');

	// Route::resource('supplier','supplierController');

	// Route::resource('kategori','kategoriController');

	// Route::resource('barang','barangController');


	//old
	// Route::get('transaksi-masuk','transaksiController@index');
	// Route::get('transaksi-masuk/create','transaksiController@create');
	// Route::get('transaksi-masuk/store','transaksiController@store')->name('transaksi-masuk.store');
	// Route::get('transaksi-masuk/show','transaksiController@show')->name('transaksi-masuk.show');

app/customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class customer extends Model
{

    protected $fillable = [
        'nama', 'alamat', 'telp',
    ];

    public function transaksi()
    {
        return $this->hasMany(transaksi::class);
    }

    use SoftDeletes;
    protected $dates =['deleted_at'];
}

app/Http/Controllers/customerController.php
<?php

namespace App\Http\Controllers;

use App\customer;
use Illuminate\Http\Request;
use App\Http\Requests;

class customerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = customer::all();
        return view ('customer.mastercustomer',compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('customer.createcustomer');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $success = 'failed';
        $customer = customer::create([
            'nama'=> $request->nama,
            'alamat'=> $request->alamat,
            'telp'=> $request->telp
        ]); {
           $success = 'success'; 
        }
        


        // Customer::create($request->all());

        return redirect()->route('customer.index')->with('alert', $success);
        // return view ('mastercustomer')->with('alert', $success);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $customers = customer::find($id);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customers = customer::find($id);
        $customer = $customers;
        return view('customer.editcustomer',compact('customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        customer::where('id', $id)->update([
            'nama' => request('nama'),
            'alamat' => request('alamat'),
            'telp' => request('telp')
        ]);

        return redirect()->route('customer.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customers = customer::findOrFail($id);
        $customers->delete();

        return redirect()->route('customer.index');
    }

}

resources/views/customer/createcustomer.blade.php
@extends('layout.default')

@section('title')
    Master Customer - Add
@endsection

@section('content')
    <div class="title_right">
        <h3><a href="{{route('customer.index')}}" class="btn-index btn btn-primary pull-right col-sm-2 col-sm-10" title="Back"><i class="fa fa-arrow-left"></i></a></h3>
    </div>
    <div class="title_left">
        <h3>Master Customer - Add</h3>
    </div>

    <div class="x_panel">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Membership</a></li>
            <li class="breadcrumb-item"><a href="#">Customer</a></li>
            <li class="breadcrumb-item"><a href="">Add</a></li>
        </ol>
        @if(session('alert'))
        <div class="alert {{ session('alert') == 'success' ? 'alert-success' : 'alert-danger' }}">
            <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span>@if(session('alert') == 'success') Customer Berhasil Ditambahkan. @else Customer Gagal Ditambahkan. @endif</span>
        </div>
        @endif
        <div class="x_content">
            <form method="post" action="{{route ('customer.store')}}" class="form-horizontal form-label-left" role="form"  name="_token" enctype="multipart/form-data">
                @if($errors->isNotEmpty())
                    <div class="alert alert-warning" role="alert">
                        @foreach($errors->all() as $error)
                            <span>{{ $error }}</span>
                            <br>
                        @endforeach
                    </div>
                @endif
                {{csrf_field()}}

                <div class="form-group">
                    <label class="control-label col-sm-3 col-xs-12">Nama</label>
                    <div class="col-sm-5 col-xs-12">
                        <input type="text" id="nama" name="nama" value="{{old('nama')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
                        @if ($errors->has('nama'))
                            <span class="help-block">
                                <strong>{{ $errors->first('nama') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-3 col-xs-12">Alamat</label>
                    <div class="col-sm-5 col-xs-12">
                        <input type="text" id="alamat" name="alamat" value="{{old('alamat')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
                        @if ($errors->has('alamat'))
                            <span class="help-block">
                                <strong>{{ $errors->first('alamat') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                    <div class="form-group">
                        <label class="control-label col-sm-3 col-xs-12">Telp</label>
                        <div class="col-sm-5 col-sm-9">
                            <input type="tel" class="form-control" data-inputmask="'mask' : '(999) 999-999-999'" id="telp" name="telp" value="{{old('telp')}}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="">
                            @if ($errors->has('telp'))
                                <span class="help-block">
                                <strong>{{ $errors->first('telp') }}</strong>
                            </span>
                            @endif
                            <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                        </div>
                    </div>
                <button class="btn btn-primary" type="submit">Add</button>
            </form>
        </div>
    </div>
@endsection

resources/views/customer/editcustomer.blade.php
@extends('layout.default')

@section('title')
    Master Customer - Edit
@endsection

@section('content')
    <div class="title_right">
        <h3><a href="{{route('customer.index')}}" class="btn-index btn btn-primary pull-right col-sm-2 col-sm-10" title="Back"><i class="fa fa-arrow-left"></i></a></h3>
    </div>
    <div class="title_left">
        <h3>Master Customer - Edit</h3>
    </div>
    <div class="x_panel">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Membership</a></li>
            <li class="breadcrumb-item"><a href="#">Customer</a></li>
            <li class="breadcrumb-item active"><a href="">Edit</a></li>
        </ol>
        @if(session('alert'))
            <div class="alert {{ session('alert') == 'success' ? 'alert-success' : 'alert-danger' }}">
                <span>@if(session('alert') == 'success') Customer Berhasil Diedit. @else customer Gagal Diedit. @endif</span>
            </div>
        @endif
        <div class="x_content">
            <form method="post" action="{{route ('customer.update', $customers->id)}}" class="form-horizontal form-label-left" role="form" >
                {{method_field('PUT')}}
                @if(/** @var \Illuminate\Support\MessageBag $errors */ $errors->isNotEmpty())
                    <div class="alert alert-warning" role="alert">
                        @foreach($errors->all() as $error)
                            <span>{{ $error }}</span>
                            <br>
                        @endforeach
                    </div>
                @endif
                {{csrf_field()}}

                <div class="form-group">
                    <label class="control-label col-sm-3 col-xs-12">Nama</label>
                    <div class="col-sm-7 col-xs-12">
                        <input type="text" id="nama" name="nama" value="{{ $customers->nama }}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="" >
                        @if ($errors->has('nama'))
                            <span class="help-block">
                                <strong>{{ $errors->first('nama') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-3 col-xs-12">Alamat</label>
                    <div class="col-sm-7 col-xs-12">
                        <input type="text" id="alamat" name="alamat" value="{{ $customers->alamat }}" required="required" class="form-control col-md-7 col-xs-12" value="" autofocus="" >
                        @if ($errors->has('alamat'))
                            <span class="help-block">
                                <strong>{{ $errors->first('alamat') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-3 col-xs-12">Telp</label>
                    <div class="col-sm-3 col-sm-9">
                        <input type="text" id="telp" name="telp" value="{{ $customers->telp}}" required="required" class="form-control col-md-7 col-xs-12"  value="" autofocus="">
                        @if ($errors->has('telp'))
                            <span class="help-block">
                                <strong>{{ $errors->first('telp') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <button class="btn btn-warning" type="/customer">Cancel</button>
                <button class="btn btn-primary" type="submit">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/customer/mastercustomer.blade.php
@extends('layout.default')

@section('title')
    Master Customer
@endsection

@section('content')
    <div class="title_right">
        <h3><a href="{{route('customer.create')}}" class="btn-index btn btn-primary pull-right col-sm-2 col-sm-10" title="Add"><i class="glyphicon glyphicon-plus"></i></a></h3>
    </div>
    <div class="title_left">
        <h3>Master Customer</h3>
    </div>

    <div class="x_panel">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Membership</a></li>
            <li class="breadcrumb-item active"><a href="">Customer</a></li>
        </ol>
        <div class="con">
            <table id="datatable-buttons" class="table table-striped table-bordered dataTable no-footer dtr-inline collapsed" role="grid" aria-describedby="datatable-buttons_info" style="width: 1031px;">
                <thead>
                <tr>
                    <th scope="col">Nama</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Telp</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($customers as $customer)
                <tr>
                    <td>{{ $customer->nama }}</td>       
                    <td>{{ $customer->alamat }}</td>
                    <td>{{ $customer->telp }}</td>
                    <td>
                        <div id="lihat-modal-{{ $customer->id}}" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">
                                            <span id="modal-title">View Master Customer</span>
                                        </h4>
                                    </div> 
                                    <form action="{{ route ('customer.show', $customer->id )}}" method="GET">
                                        <div class="modal-body" value="{{ $customer->id }}">
                                        @method('GET')
                                            @csrf
                                        <div class="form-group">
                                            <label>ID</label>
                                            <div>
                                                <input type="text" class="form-control" id="id" name="id" value="{{ $customer->id }}" disabled="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Nama</label>
                                            <div>
                                                <input type="text" class="form-control" id="nama" name="nama" value="{{ $customer->nama }}" disabled="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Alamat</label>
                                            <div>
                                                <input type="text" class="form-control" id="alamat" name="alamat" value="{{ $customer->alamat }}" disabled="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Telp</label>
                                            <div>
                                                <input type="text" class="form-control" id="telp" name="telp" value="{{ $customer->telp }}"disabled="" >
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Date Created</label>
                                            <div>
                                                <input type="text" class="form-control" id="created_at" name="created_at" value="{{ $customer->created_at }}" disabled="">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Last Modifield</label>
                                            <div>
                                                <input type="text" class="form-control" id="updated_at" name="updated_at" value="{{ $customer->updated_at }}" disabled="">
                                            </div>
                                        </div>

                                    </div>
                                    </form>
                                    
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="hapus-modal-{{ $customer->id  }}" class="modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                        <h4 class="modal-title">
                                            <!-- Beri id "modal-title" untuk tag span pada judul modal -->
                                            <span id="modal-title">Apakah anda ingin menghapus...?</span>
                                        </h4>
                                    </div>
                                    <div class="modal-footer">
                                        <form action="{{ route ('customer.destroy', $customer->id )}}" method="post">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-default">Ya</button>
                                        </form>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <a href="#"  data-toggle="modal" data-target="#lihat-modal-{{ $customer->id}}" class="btn btn-primary glyphicon glyphicon-eye-open" title="View"></a>

                        {{--<button class="btn btn-primary glyphicon glyphicon-eye-open" title="View" type="submit"></button>--}}
                        <a href="{{route('customer.edit',$customer->id)}}" class="btn btn-info glyphicon glyphicon-edit" title="Edit"></a>
                        <button data-toggle="modal" data-target="#hapus-modal-{{ $customer->id  }}" class="btn btn-danger glyphicon glyphicon-trash"></button>
                    </td>
                </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div>
@endsection